### ISSUE TITLE
false negatives with nx:affected and cache

### ISSUE THREAD

**Issue by smasala** [percy/exec-action#27]
If you run percy with nx and cypress and only those tests that were affected by your changes. It can be that the following happens:

- cache results are pulled from nx cloud (tests aren't rerun, only the result is returned from the previous run)
- the e2e test doesn't generate a percy snapshot (mono-repo not all tests use percy)

Both cases cause percy action to "fail" although both could result in successful cypress runs.

**Comment by Robdel12** [comment]
Hey @smasala! This isn't exactly related to the exec-action (it's how Percy works as a product). 

> Both cases cause percy action to "fail" although both could result in successful cypress runs.

Percy will never fail your CI run or your test run. This is because Percy is pretty async to your testing process. The Percy build isn't finalized until all the tests complete. You can use `percy build:wait` to poll for build results, and then fail CI there if you wish. 

> the e2e test doesn't generate a percy snapshot (mono-repo not all tests use percy)

This won't work well with Percy -- you can do this with PR branches (and create a partial build: https://docs.percy.io/docs/partial-builds). But baseline branch builds will need the full shape, each time (by default this is any branch on `master`). If a baseline is run without the full set of snapshots, your new baseline will be missing snapshots. 

Hope this helps! :)

**Comment by smasala** [comment]
@Robdel12 thanks for getting back to me.

You're correct. The exec perhaps isn't the right culprit here, but the cli or PR app that informs if there are any visual changes needing review will mark as failed / error as it may not have received any new snapshots to compare. Especially if nx runs in cached mode.

Since cypress seems to run inside percy cli, you'd imagine that if cypress gives you the all green regardless of whether it actually ran the tests (not just returned a cached computation hash) that percy check wouldn't report errors but more a "nothing changed" status.

The problem is that we must alter our pipeline to always check to see if any tests are affected first, if not, skip the entire step (otherwise percy will through an error that no snapshots were received) or run the affected tests in non cached mode and lose the benefits of computation caching. Both which are unnecessary imo 🤷‍♂️
